export function queryElements() {
    const get = (id) => document.getElementById(id);
    return {
        language: get('language'),
        apiKeyProvider: get('apiKeyProvider'),
        apiKeyInput: get('apiKeyInput'),
        apiKeyPreview: get('apiKeyPreview'),
        apiKeySave: get('apiKeySave'),
        apiKeyClear: get('apiKeyClear'),
        apiKeyIssue: get('apiKeyIssue'),
        apiKeyStatusRow: get('apiKeyStatusRow'),
        generate: get('generate'),
        apply: get('apply'),
        includeUnstaged: get('includeUnstaged'),
        includeUntracked: get('includeUntracked'),
        includeBinary: get('includeBinary'),
        maxPromptMode: get('maxPromptMode'),
        maxPromptValue: get('maxPromptValue'),
        prompt: get('prompt'),
        promptSaved: get('promptSaved'),
        promptPreset: get('promptPreset'),
        presetName: get('presetName'),
        presetAdd: get('presetAdd'),
        presetDelete: get('presetDelete'),
        provider: get('provider'),
        providerRow: get('providerRow'),
        providerHelp: get('providerHelp'),
        model: get('model'),
        modelGroup: get('modelGroup'),
        modelHelp: get('modelHelp'),
        customModelRow: get('customModelRow'),
        customModel: get('customModel'),
        reasoning: get('reasoning'),
        verbosity: get('verbosity'),
        reasoningRow: get('reasoningRow'),
        verbosityRow: get('verbosityRow'),
        statusRow: get('statusRow'),
        result: get('result'),
        errorSection: get('errorSection'),
        errorBox: get('errorBox')
    };
}
