function queryElements(): PanelElements {
  // HTML の ID と要素の型をここで対応付け、イベント処理では型を断定しない。
  const get = <T extends HTMLElement = HTMLElement>(id: string): T | null => document.getElementById(id) as T | null;
  return {
    language: get<HTMLSelectElement>('language'),
    apiKeySection: get('apiKeySection'),
    apiKeyCloudPanel: get('apiKeyCloudPanel'),
    apiKeyProvider: get<HTMLSelectElement>('apiKeyProvider'),
    apiKeyInput: get<HTMLInputElement>('apiKeyInput'),
    apiKeyPreview: get('apiKeyPreview'),
    apiKeySave: get<HTMLButtonElement>('apiKeySave'),
    apiKeyClear: get<HTMLButtonElement>('apiKeyClear'),
    apiKeyIssue: get<HTMLButtonElement>('apiKeyIssue'),
    apiKeyStatusRow: get('apiKeyStatusRow'),
    generate: get<HTMLButtonElement>('generate'),
    apply: get<HTMLButtonElement>('apply'),
    includeUnstaged: get<HTMLInputElement>('includeUnstaged'),
    includeUntracked: get<HTMLInputElement>('includeUntracked'),
    includeBinary: get<HTMLInputElement>('includeBinary'),
    maxPromptMode: get<HTMLSelectElement>('maxPromptMode'),
    maxPromptValue: get<HTMLInputElement>('maxPromptValue'),
    prompt: get<HTMLTextAreaElement>('prompt'),
    promptSaved: get('promptSaved'),
    promptPreset: get<HTMLSelectElement>('promptPreset'),
    presetName: get<HTMLInputElement>('presetName'),
    presetAdd: get<HTMLButtonElement>('presetAdd'),
    presetDelete: get<HTMLButtonElement>('presetDelete'),
    provider: get<HTMLSelectElement>('provider'),
    providerRow: get('providerRow'),
    model: get<HTMLSelectElement>('model'),
    modelGroup: get('modelGroup'),
    customModelRow: get('customModelRow'),
    customModel: get<HTMLInputElement>('customModel'),
    localModelPanel: get('localModelPanel'),
    localModelName: get<HTMLSelectElement>('localModelName'),
    localModelStatus: get('localModelStatus'),
    localModelGuidance: get('localModelGuidance'),
    localModelGuidanceBadge: get('localModelGuidanceBadge'),
    localModelGuidanceSize: get('localModelGuidanceSize'),
    localModelGuidanceText: get('localModelGuidanceText'),
    localModelGuidanceDetails: get('localModelGuidanceDetails'),
    localModelDownload: get<HTMLButtonElement>('localModelDownload'),
    localModelCancel: get<HTMLButtonElement>('localModelCancel'),
    localModelDelete: get<HTMLButtonElement>('localModelDelete'),
    localModelTest: get<HTMLButtonElement>('localModelTest'),
    localModelHint: get('localModelHint'),
    codexAuthPanel: get('codexAuthPanel'),
    codexAuthStatus: get('codexAuthStatus'),
    codexAuthHint: get('codexAuthHint'),
    codexAuthLogin: get<HTMLButtonElement>('codexAuthLogin'),
    codexAuthRefresh: get<HTMLButtonElement>('codexAuthRefresh'),
    codexAuthLogout: get<HTMLButtonElement>('codexAuthLogout'),
    reasoningLabel: get('reasoningLabel'),
    reasoning: get<HTMLSelectElement>('reasoning'),
    verbosity: get<HTMLSelectElement>('verbosity'),
    reasoningRow: get('reasoningRow'),
    verbosityRow: get('verbosityRow'),
    statusRow: get('statusRow'),
    result: get('result'),
    errorSection: get('errorSection'),
    errorBox: get('errorBox')
  };
}

window.CommitMakerElements = { queryElements };
