name: Publish Extension (Stable)

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read

jobs:
  publish-stable:
    uses: ./.github/workflows/_publish-core.yml
    with:
      channel: stable
      pre_release: false
    secrets:
      VSCE_PAT: ${{ secrets.VSCE_PAT }}
      OVSX_PAT: ${{ secrets.OVSX_PAT }}
