name: Publish Extension (Stable)

on:
  push:
    tags:
      - "v*"

jobs:
  publish-stable:
    uses: ./.github/workflows/_publish-core.yml
    with:
      channel: stable
      pre_release: false
    secrets: inherit
