name: Publish Extension (Preview)

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish-preview:
    uses: ./.github/workflows/_publish-core.yml
    with:
      channel: preview
      pre_release: true
    secrets: inherit
